---
- name: ftp client installed
  hosts: dns-servers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: latest lftp version installed
    yum:
      name: lftp
      state: latest
