# This is my first playbook

- name: get uptime on all 
  hosts: all
  user:	ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
      - name: get uptime
        shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
        changed_when: False
        register: uptime

      - debug: var={{ item }}
        with_items:
          - uptime.stdout
